//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectProducts.Data
{

    public partial class Products
    {
        public int Id_Product { get; set; }
        public string NameProduct { get; set; }
        public string ProductDescription { get; set; }
        public int Id_Category { get; set; }
        public string image { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
